spring.datasource.url=jdbc:postgresql://localhost:5432/telegrambot
spring.datasource.username=bankadmin
spring.datasource.password=bankadmin
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml