-- liquibase formatted sql

-- changeset vladimirs_anufrijevs:add_notification_task_table

create table if not exists notification_task (
 id bigint generated by default as identity primary key,
 chat_id bigint not null,
 message_text text not null,
 notification_date_time timestamp not null
)